Tests and basic operation
PhotostatEditor/libphotostat pull request #2
Opened 2021-09-01 12:35 UTC by AshishS-1123

# TODO

- Created basic feature for Reading and writing images.
- Created setup for tests.

*Still a work in progress*

2021-09-01 13:49 UTC, Abdallah-Moh commented on src/ImageIO/Writer.vala
> +    public Writer () {
Add `class` after public

2021-09-01 13:50 UTC, Abdallah-Moh commented on src/ImageIO/Displayer.vala
> +public LibPhotostat.ImageIO.Displayer {
add `class` here too

2021-09-05 05:27 UTC, AshishS-1123 commented
@Abdallah-Moh can you take a look at the meson file. I had to make some changes and removed a lot of things because I was getting a compile error. Make sure ```ninja test``` works afterwards.

2021-09-05 07:40 UTC, Abdallah-Moh commented
It works

2021-09-29 17:12 UTC, colinkiama requested changes
AbstractOperation should marked as an **abstract** class.

2021-10-04 09:34 UTC, colinkiama approved these changes

2021-10-04 09:53 UTC, Abdallah-Moh approved these changes

2021-10-04 09:53 UTC, merged