Improvement In AbstractOperation and Some Point Operations
PhotostatEditor/libphotostat pull request #3
Opened 2021-10-21 15:47 UTC by AshishS-1123

# Summary 

## Changes in Abstract Operation

- **set_parameter** - This method will be used for providing metadata for the operation. 
Usually, operations or brushes need some parameters for processing. Since each operation will have a bunch of different parameters, it will be hard for developers to keep track of the names of those parameters and their setters. This method gives us a convenient and universal way to set parameters.
- **set_operation_bounds** - This method will specify the region of the image over which to apply the operation.

## Changes in Image

**Image** has a number of new convenience functions for
- Cloning Images
- Creating Empty Images
- Getting and Setting Values of Specific Pixels

## Point Operation

Point operations are those operations that calculate the new value of a pixel based on its previous value. In this PR, I have developed point operations for **Brightness**, **Contrast** and **Inversion**.
This mainly serve as proof-of-concept for the upgrades to AbstractOperation, and also allow us to develop some tools in the App.

## Tests

I haven't made any major changes to how tests are organised or executed, but this PR should lay a few guidelines for how to write them.
Since we are adopting TDD, our approach will be to write tests first and lay down the functionality and then do the implementation.
Hence, the unittests must check that all the essential methods from **AbstractOperation** have been implemented (like the set_parameters and set_operation_bounds methods). This will ensure (both to the developer and to the reviewer) that the behaviour is being controlled by standard methods. It will also check the correctness of implementation (for example, when developing an operation, it is very easy to apply the operation on the whole image rather than the operation bounds.).

# Testing Changes

- Run ```meson build`` from root directory. This step need not be done for every compile.
- Then ```cd build`` to go to the build directory.
- Then run ```ninja test``` to run all the unittests. This will show you the names of tests that were successful and otherwise.

2021-10-21 19:24 UTC, colinkiama approved these changes

2021-10-21 19:26 UTC, colinkiama reviewed
When we get a good amount of tests, it would be nice to add test completion results for each test unit too

2021-10-21 20:14 UTC, ghost requested changes
Some formatting fixes

2021-10-21 20:14 UTC, Abdallah-Moh commented on src/PointOps/BrightnessContrast.vala
> +                processed.set_pixel(i, j, red, green, blue, alpha);
```suggestion
                processed.set_pixel (i, j, red, green, blue, alpha);
```

2021-10-21 20:14 UTC, Abdallah-Moh commented on src/PointOps/BrightnessContrast.vala
> +                warning ("""Invalid parameter %s given to BrightnessContrast operation.""".printf(parameter));
```suggestion
                warning ("""Invalid parameter %s given to BrightnessContrast operation.""".printf (parameter));
```

2021-10-21 20:14 UTC, Abdallah-Moh commented on src/PointOps/Inversion.vala
> +        warning ("""Invalid parameter %s given to Inversion operation.""".printf(parameter));
```suggestion
        warning ("""Invalid parameter %s given to Inversion operation.""".printf (parameter));
```

2021-10-21 20:14 UTC, Abdallah-Moh commented on tests/PointOps/test_Inversion.vala
> +void test_bounds_effect ()  {
```suggestion
void test_bounds_effect () {
```

2021-10-21 20:21 UTC, Abdallah-Moh commented on src/Image.vala
> +    public enum FORMAT {
Shouldn't this be `static` ?

2021-10-23 05:42 UTC, AshishS-1123 commented on src/Image.vala
> +    public enum FORMAT {
@Abdallah-Moh **enum** already has static like behaviour. You can access it by referencing the class name as such
```vala
LibPhotostat.Image.FORMAT.RGB
```
So there is no need for the **static** keyword. Adding the keyword gives syntax error anyway.

2021-10-26 18:18 UTC, ghost commented on src/Utils/Maths.vala
> +        }
No need for an if statement just use
```suggestion
        value = value > 255 ? 255 : (value < 0 ? 0 : value)
```

2021-10-27 08:09 UTC, AshishS-1123 commented on src/Utils/Maths.vala
> +        }
@Abdallah-Moh I will commit this suggestion. But doesn't this make the code a little harder to read?

2021-10-27 12:08 UTC, ghost commented on src/Utils/Maths.vala
> +        }
A comment will do the trick

2021-10-28 13:55 UTC, merged